### ISSUE TITLE
Multiple charts, only one legend

### ISSUE THREAD

**Issue by sambengtson** [CodeYellowBV/chartist-plugin-legend#33]
I'm experiencing an issue that was reported on the [Gitlab Repo](https://gitlab.com/CodeYellowBV/chartist-plugin-legend/issues/17)

If I have multiple charts with legends on a single page using id's to select them, it seems that the last chart is the only one that gets a legend generated.  It does not seem to matter what type of chart I use.  I can give a reproducible example if necessary.

![capture](https://cloud.githubusercontent.com/assets/5069583/21484403/8add6518-cb57-11e6-9588-4b2fa928ec4d.PNG)

**Comment by SpaceK33z** [comment]
Yes, I'd like a reproducible example. On the [example page](https://codeyellowbv.github.io/chartist-plugin-legend/) you can see that this works. However, do note that I don't use this package myself much anymore, so please consider sending a PR with the fix (and a test).

PS: the GitLab repo was for demoing purposes, you can also find that issue here: https://github.com/CodeYellowBV/chartist-plugin-legend/issues/17.

**Comment by sambengtson** [comment]
Seems that I was using a pretty old version of the lib from a bower install.  Everything appears to be good now.  

I'll keep my eye open for other issues and will submit PRs as necessary.  I plan on using this for the foreseeable future.  Thanks!

**Comment by GabrielSiq** [comment]
I had a similar problem, also due to the version installed through bower being old.
